services:
  webui:
    build: .
    ports:
      - 8000:8000
    networks:
      - pg-network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - pg-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  pg-data:

networks:
  pg-network:
