services:
  webui:
    build: .
    ports:
      - 8000:8000
    networks:
      - pg-network
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - pg-network

volumes:
  pg-data:

networks:
  pg-network:
